name: route_task
description: "Route Task"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.8.4
  get_it: ^7.6.4
  mockito: ^5.4.2
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  injectable: ^2.3.2
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  lint: ^2.3.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/

